// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: service_price.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 计算费用
type CalculatePriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PriceType    string  `protobuf:"bytes,1,opt,name=priceType,proto3" json:"priceType,omitempty"`
	TrafficGB    float64 `protobuf:"fixed64,2,opt,name=trafficGB,proto3" json:"trafficGB,omitempty"`
	BandwidthMB  float64 `protobuf:"fixed64,3,opt,name=bandwidthMB,proto3" json:"bandwidthMB,omitempty"`
	NodeRegionId int64   `protobuf:"varint,4,opt,name=nodeRegionId,proto3" json:"nodeRegionId,omitempty"`
}

func (x *CalculatePriceRequest) Reset() {
	*x = CalculatePriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_price_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculatePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePriceRequest) ProtoMessage() {}

func (x *CalculatePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_price_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePriceRequest.ProtoReflect.Descriptor instead.
func (*CalculatePriceRequest) Descriptor() ([]byte, []int) {
	return file_service_price_proto_rawDescGZIP(), []int{0}
}

func (x *CalculatePriceRequest) GetPriceType() string {
	if x != nil {
		return x.PriceType
	}
	return ""
}

func (x *CalculatePriceRequest) GetTrafficGB() float64 {
	if x != nil {
		return x.TrafficGB
	}
	return 0
}

func (x *CalculatePriceRequest) GetBandwidthMB() float64 {
	if x != nil {
		return x.BandwidthMB
	}
	return 0
}

func (x *CalculatePriceRequest) GetNodeRegionId() int64 {
	if x != nil {
		return x.NodeRegionId
	}
	return 0
}

type CalculatePriceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount             float64 `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	HasNodeRegionPrice bool    `protobuf:"varint,2,opt,name=hasNodeRegionPrice,proto3" json:"hasNodeRegionPrice,omitempty"`
}

func (x *CalculatePriceResponse) Reset() {
	*x = CalculatePriceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_price_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalculatePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePriceResponse) ProtoMessage() {}

func (x *CalculatePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_price_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePriceResponse.ProtoReflect.Descriptor instead.
func (*CalculatePriceResponse) Descriptor() ([]byte, []int) {
	return file_service_price_proto_rawDescGZIP(), []int{1}
}

func (x *CalculatePriceResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CalculatePriceResponse) GetHasNodeRegionPrice() bool {
	if x != nil {
		return x.HasNodeRegionPrice
	}
	return false
}

var File_service_price_proto protoreflect.FileDescriptor

var file_service_price_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x99, 0x01, 0x0a, 0x15, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x47, 0x42, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x47, 0x42, 0x12,
	0x20, 0x0a, 0x0b, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x4d, 0x42, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x62, 0x61, 0x6e, 0x64, 0x77, 0x69, 0x64, 0x74, 0x68, 0x4d,
	0x42, 0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x60, 0x0a, 0x16, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x12, 0x68, 0x61, 0x73, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x12, 0x68, 0x61, 0x73, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x50, 0x72, 0x69, 0x63, 0x65, 0x32, 0x57, 0x0a, 0x0c, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x63, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_price_proto_rawDescOnce sync.Once
	file_service_price_proto_rawDescData = file_service_price_proto_rawDesc
)

func file_service_price_proto_rawDescGZIP() []byte {
	file_service_price_proto_rawDescOnce.Do(func() {
		file_service_price_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_price_proto_rawDescData)
	})
	return file_service_price_proto_rawDescData
}

var file_service_price_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_price_proto_goTypes = []interface{}{
	(*CalculatePriceRequest)(nil),  // 0: pb.CalculatePriceRequest
	(*CalculatePriceResponse)(nil), // 1: pb.CalculatePriceResponse
}
var file_service_price_proto_depIdxs = []int32{
	0, // 0: pb.PriceService.calculatePrice:input_type -> pb.CalculatePriceRequest
	1, // 1: pb.PriceService.calculatePrice:output_type -> pb.CalculatePriceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_price_proto_init() }
func file_service_price_proto_init() {
	if File_service_price_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_price_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculatePriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_price_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalculatePriceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_price_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_price_proto_goTypes,
		DependencyIndexes: file_service_price_proto_depIdxs,
		MessageInfos:      file_service_price_proto_msgTypes,
	}.Build()
	File_service_price_proto = out.File
	file_service_price_proto_rawDesc = nil
	file_service_price_proto_goTypes = nil
	file_service_price_proto_depIdxs = nil
}
