// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: service_ns_route.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建自定义线路
type CreateNSRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsClusterId       int64  `protobuf:"varint,1,opt,name=nsClusterId,proto3" json:"nsClusterId,omitempty"`
	NsDomainId        int64  `protobuf:"varint,2,opt,name=nsDomainId,proto3" json:"nsDomainId,omitempty"`
	UserId            int64  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Name              string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	RangesJSON        []byte `protobuf:"bytes,5,opt,name=rangesJSON,proto3" json:"rangesJSON,omitempty"`
	IsPublic          bool   `protobuf:"varint,6,opt,name=isPublic,proto3" json:"isPublic,omitempty"`                   // 是否公用
	NsRouteCategoryId int64  `protobuf:"varint,7,opt,name=nsRouteCategoryId,proto3" json:"nsRouteCategoryId,omitempty"` // 分类ID
	Priority          int32  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`                   // 优先级
}

func (x *CreateNSRouteRequest) Reset() {
	*x = CreateNSRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNSRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNSRouteRequest) ProtoMessage() {}

func (x *CreateNSRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNSRouteRequest.ProtoReflect.Descriptor instead.
func (*CreateNSRouteRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNSRouteRequest) GetNsClusterId() int64 {
	if x != nil {
		return x.NsClusterId
	}
	return 0
}

func (x *CreateNSRouteRequest) GetNsDomainId() int64 {
	if x != nil {
		return x.NsDomainId
	}
	return 0
}

func (x *CreateNSRouteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateNSRouteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateNSRouteRequest) GetRangesJSON() []byte {
	if x != nil {
		return x.RangesJSON
	}
	return nil
}

func (x *CreateNSRouteRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *CreateNSRouteRequest) GetNsRouteCategoryId() int64 {
	if x != nil {
		return x.NsRouteCategoryId
	}
	return 0
}

func (x *CreateNSRouteRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type CreateNSRouteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsRouteId int64 `protobuf:"varint,1,opt,name=nsRouteId,proto3" json:"nsRouteId,omitempty"`
}

func (x *CreateNSRouteResponse) Reset() {
	*x = CreateNSRouteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateNSRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNSRouteResponse) ProtoMessage() {}

func (x *CreateNSRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNSRouteResponse.ProtoReflect.Descriptor instead.
func (*CreateNSRouteResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNSRouteResponse) GetNsRouteId() int64 {
	if x != nil {
		return x.NsRouteId
	}
	return 0
}

// 修改自定义线路
type UpdateNSRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsRouteId         int64  `protobuf:"varint,1,opt,name=nsRouteId,proto3" json:"nsRouteId,omitempty"`
	Name              string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RangesJSON        []byte `protobuf:"bytes,3,opt,name=rangesJSON,proto3" json:"rangesJSON,omitempty"`
	IsPublic          bool   `protobuf:"varint,4,opt,name=isPublic,proto3" json:"isPublic,omitempty"`                   // 是否公用
	NsRouteCategoryId int64  `protobuf:"varint,5,opt,name=nsRouteCategoryId,proto3" json:"nsRouteCategoryId,omitempty"` // 分类ID
	Priority          int32  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`                   // 优先级
	IsOn              bool   `protobuf:"varint,6,opt,name=isOn,proto3" json:"isOn,omitempty"`
}

func (x *UpdateNSRouteRequest) Reset() {
	*x = UpdateNSRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNSRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNSRouteRequest) ProtoMessage() {}

func (x *UpdateNSRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNSRouteRequest.ProtoReflect.Descriptor instead.
func (*UpdateNSRouteRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateNSRouteRequest) GetNsRouteId() int64 {
	if x != nil {
		return x.NsRouteId
	}
	return 0
}

func (x *UpdateNSRouteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateNSRouteRequest) GetRangesJSON() []byte {
	if x != nil {
		return x.RangesJSON
	}
	return nil
}

func (x *UpdateNSRouteRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *UpdateNSRouteRequest) GetNsRouteCategoryId() int64 {
	if x != nil {
		return x.NsRouteCategoryId
	}
	return 0
}

func (x *UpdateNSRouteRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *UpdateNSRouteRequest) GetIsOn() bool {
	if x != nil {
		return x.IsOn
	}
	return false
}

// 删除自定义线路
type DeleteNSRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsRouteId int64 `protobuf:"varint,1,opt,name=nsRouteId,proto3" json:"nsRouteId,omitempty"`
}

func (x *DeleteNSRouteRequest) Reset() {
	*x = DeleteNSRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteNSRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNSRouteRequest) ProtoMessage() {}

func (x *DeleteNSRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNSRouteRequest.ProtoReflect.Descriptor instead.
func (*DeleteNSRouteRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteNSRouteRequest) GetNsRouteId() int64 {
	if x != nil {
		return x.NsRouteId
	}
	return 0
}

// 获取单个自定义路线信息
type FindNSRouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsRouteId int64 `protobuf:"varint,1,opt,name=nsRouteId,proto3" json:"nsRouteId,omitempty"`
}

func (x *FindNSRouteRequest) Reset() {
	*x = FindNSRouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindNSRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNSRouteRequest) ProtoMessage() {}

func (x *FindNSRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNSRouteRequest.ProtoReflect.Descriptor instead.
func (*FindNSRouteRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{4}
}

func (x *FindNSRouteRequest) GetNsRouteId() int64 {
	if x != nil {
		return x.NsRouteId
	}
	return 0
}

type FindNSRouteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsRoute *NSRoute `protobuf:"bytes,1,opt,name=nsRoute,proto3" json:"nsRoute,omitempty"`
}

func (x *FindNSRouteResponse) Reset() {
	*x = FindNSRouteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindNSRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindNSRouteResponse) ProtoMessage() {}

func (x *FindNSRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindNSRouteResponse.ProtoReflect.Descriptor instead.
func (*FindNSRouteResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{5}
}

func (x *FindNSRouteResponse) GetNsRoute() *NSRoute {
	if x != nil {
		return x.NsRoute
	}
	return nil
}

// 查询自定义线路数量
type CountAllNSRoutesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsClusterId int64 `protobuf:"varint,1,opt,name=nsClusterId,proto3" json:"nsClusterId,omitempty"`
	NsDomainId  int64 `protobuf:"varint,2,opt,name=nsDomainId,proto3" json:"nsDomainId,omitempty"`
	UserId      int64 `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *CountAllNSRoutesRequest) Reset() {
	*x = CountAllNSRoutesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountAllNSRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountAllNSRoutesRequest) ProtoMessage() {}

func (x *CountAllNSRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountAllNSRoutesRequest.ProtoReflect.Descriptor instead.
func (*CountAllNSRoutesRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{6}
}

func (x *CountAllNSRoutesRequest) GetNsClusterId() int64 {
	if x != nil {
		return x.NsClusterId
	}
	return 0
}

func (x *CountAllNSRoutesRequest) GetNsDomainId() int64 {
	if x != nil {
		return x.NsDomainId
	}
	return 0
}

func (x *CountAllNSRoutesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 读取所有自定义线路
type FindAllNSRoutesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsClusterId       int64 `protobuf:"varint,1,opt,name=nsClusterId,proto3" json:"nsClusterId,omitempty"`             // 集群ID
	NsDomainId        int64 `protobuf:"varint,2,opt,name=nsDomainId,proto3" json:"nsDomainId,omitempty"`               // 域名ID
	UserId            int64 `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`                       // 用户ID
	NsRouteCategoryId int64 `protobuf:"varint,4,opt,name=nsRouteCategoryId,proto3" json:"nsRouteCategoryId,omitempty"` // 线路分类ID
}

func (x *FindAllNSRoutesRequest) Reset() {
	*x = FindAllNSRoutesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllNSRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllNSRoutesRequest) ProtoMessage() {}

func (x *FindAllNSRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllNSRoutesRequest.ProtoReflect.Descriptor instead.
func (*FindAllNSRoutesRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{7}
}

func (x *FindAllNSRoutesRequest) GetNsClusterId() int64 {
	if x != nil {
		return x.NsClusterId
	}
	return 0
}

func (x *FindAllNSRoutesRequest) GetNsDomainId() int64 {
	if x != nil {
		return x.NsDomainId
	}
	return 0
}

func (x *FindAllNSRoutesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FindAllNSRoutesRequest) GetNsRouteCategoryId() int64 {
	if x != nil {
		return x.NsRouteCategoryId
	}
	return 0
}

type FindAllNSRoutesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsRoutes []*NSRoute `protobuf:"bytes,1,rep,name=nsRoutes,proto3" json:"nsRoutes,omitempty"`
}

func (x *FindAllNSRoutesResponse) Reset() {
	*x = FindAllNSRoutesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllNSRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllNSRoutesResponse) ProtoMessage() {}

func (x *FindAllNSRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllNSRoutesResponse.ProtoReflect.Descriptor instead.
func (*FindAllNSRoutesResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{8}
}

func (x *FindAllNSRoutesResponse) GetNsRoutes() []*NSRoute {
	if x != nil {
		return x.NsRoutes
	}
	return nil
}

// 读取所有公用的自定义线路
type FindAllPublicRoutesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindAllPublicRoutesRequest) Reset() {
	*x = FindAllPublicRoutesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllPublicRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllPublicRoutesRequest) ProtoMessage() {}

func (x *FindAllPublicRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllPublicRoutesRequest.ProtoReflect.Descriptor instead.
func (*FindAllPublicRoutesRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{9}
}

type FindAllPublicRoutesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsRoutes []*NSRoute `protobuf:"bytes,1,rep,name=nsRoutes,proto3" json:"nsRoutes,omitempty"`
}

func (x *FindAllPublicRoutesResponse) Reset() {
	*x = FindAllPublicRoutesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllPublicRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllPublicRoutesResponse) ProtoMessage() {}

func (x *FindAllPublicRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllPublicRoutesResponse.ProtoReflect.Descriptor instead.
func (*FindAllPublicRoutesResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{10}
}

func (x *FindAllPublicRoutesResponse) GetNsRoutes() []*NSRoute {
	if x != nil {
		return x.NsRoutes
	}
	return nil
}

// 设置自定义线路排序
type UpdateNSRouteOrdersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsRouteIds []int64 `protobuf:"varint,1,rep,packed,name=nsRouteIds,proto3" json:"nsRouteIds,omitempty"`
}

func (x *UpdateNSRouteOrdersRequest) Reset() {
	*x = UpdateNSRouteOrdersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateNSRouteOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNSRouteOrdersRequest) ProtoMessage() {}

func (x *UpdateNSRouteOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNSRouteOrdersRequest.ProtoReflect.Descriptor instead.
func (*UpdateNSRouteOrdersRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateNSRouteOrdersRequest) GetNsRouteIds() []int64 {
	if x != nil {
		return x.NsRouteIds
	}
	return nil
}

// 根据版本列出一组自定义线路
type ListNSRoutesAfterVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version int64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Size    int64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ListNSRoutesAfterVersionRequest) Reset() {
	*x = ListNSRoutesAfterVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNSRoutesAfterVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNSRoutesAfterVersionRequest) ProtoMessage() {}

func (x *ListNSRoutesAfterVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNSRoutesAfterVersionRequest.ProtoReflect.Descriptor instead.
func (*ListNSRoutesAfterVersionRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{12}
}

func (x *ListNSRoutesAfterVersionRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ListNSRoutesAfterVersionRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListNSRoutesAfterVersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsRoutes []*NSRoute `protobuf:"bytes,1,rep,name=nsRoutes,proto3" json:"nsRoutes,omitempty"`
}

func (x *ListNSRoutesAfterVersionResponse) Reset() {
	*x = ListNSRoutesAfterVersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListNSRoutesAfterVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNSRoutesAfterVersionResponse) ProtoMessage() {}

func (x *ListNSRoutesAfterVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNSRoutesAfterVersionResponse.ProtoReflect.Descriptor instead.
func (*ListNSRoutesAfterVersionResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{13}
}

func (x *ListNSRoutesAfterVersionResponse) GetNsRoutes() []*NSRoute {
	if x != nil {
		return x.NsRoutes
	}
	return nil
}

// 查找默认的世界区域线路
type FindAllDefaultWorldRegionRoutesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindAllDefaultWorldRegionRoutesRequest) Reset() {
	*x = FindAllDefaultWorldRegionRoutesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllDefaultWorldRegionRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllDefaultWorldRegionRoutesRequest) ProtoMessage() {}

func (x *FindAllDefaultWorldRegionRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllDefaultWorldRegionRoutesRequest.ProtoReflect.Descriptor instead.
func (*FindAllDefaultWorldRegionRoutesRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{14}
}

type FindAllDefaultWorldRegionRoutesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsRoutes []*NSRoute `protobuf:"bytes,1,rep,name=nsRoutes,proto3" json:"nsRoutes,omitempty"`
}

func (x *FindAllDefaultWorldRegionRoutesResponse) Reset() {
	*x = FindAllDefaultWorldRegionRoutesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllDefaultWorldRegionRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllDefaultWorldRegionRoutesResponse) ProtoMessage() {}

func (x *FindAllDefaultWorldRegionRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllDefaultWorldRegionRoutesResponse.ProtoReflect.Descriptor instead.
func (*FindAllDefaultWorldRegionRoutesResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{15}
}

func (x *FindAllDefaultWorldRegionRoutesResponse) GetNsRoutes() []*NSRoute {
	if x != nil {
		return x.NsRoutes
	}
	return nil
}

// 查找默认的中国省份线路
type FindAllDefaultChinaProvinceRoutesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindAllDefaultChinaProvinceRoutesRequest) Reset() {
	*x = FindAllDefaultChinaProvinceRoutesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllDefaultChinaProvinceRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllDefaultChinaProvinceRoutesRequest) ProtoMessage() {}

func (x *FindAllDefaultChinaProvinceRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllDefaultChinaProvinceRoutesRequest.ProtoReflect.Descriptor instead.
func (*FindAllDefaultChinaProvinceRoutesRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{16}
}

type FindAllDefaultChinaProvinceRoutesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsRoutes []*NSRoute `protobuf:"bytes,1,rep,name=nsRoutes,proto3" json:"nsRoutes,omitempty"`
}

func (x *FindAllDefaultChinaProvinceRoutesResponse) Reset() {
	*x = FindAllDefaultChinaProvinceRoutesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllDefaultChinaProvinceRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllDefaultChinaProvinceRoutesResponse) ProtoMessage() {}

func (x *FindAllDefaultChinaProvinceRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllDefaultChinaProvinceRoutesResponse.ProtoReflect.Descriptor instead.
func (*FindAllDefaultChinaProvinceRoutesResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{17}
}

func (x *FindAllDefaultChinaProvinceRoutesResponse) GetNsRoutes() []*NSRoute {
	if x != nil {
		return x.NsRoutes
	}
	return nil
}

// 查找默认的ISP线路
type FindAllDefaultISPRoutesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindAllDefaultISPRoutesRequest) Reset() {
	*x = FindAllDefaultISPRoutesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllDefaultISPRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllDefaultISPRoutesRequest) ProtoMessage() {}

func (x *FindAllDefaultISPRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllDefaultISPRoutesRequest.ProtoReflect.Descriptor instead.
func (*FindAllDefaultISPRoutesRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{18}
}

type FindAllDefaultISPRoutesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsRoutes []*NSRoute `protobuf:"bytes,1,rep,name=nsRoutes,proto3" json:"nsRoutes,omitempty"`
}

func (x *FindAllDefaultISPRoutesResponse) Reset() {
	*x = FindAllDefaultISPRoutesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllDefaultISPRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllDefaultISPRoutesResponse) ProtoMessage() {}

func (x *FindAllDefaultISPRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllDefaultISPRoutesResponse.ProtoReflect.Descriptor instead.
func (*FindAllDefaultISPRoutesResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{19}
}

func (x *FindAllDefaultISPRoutesResponse) GetNsRoutes() []*NSRoute {
	if x != nil {
		return x.NsRoutes
	}
	return nil
}

// 查找默认的搜索引擎线路
type FindAllAgentNSRoutesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindAllAgentNSRoutesRequest) Reset() {
	*x = FindAllAgentNSRoutesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllAgentNSRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllAgentNSRoutesRequest) ProtoMessage() {}

func (x *FindAllAgentNSRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllAgentNSRoutesRequest.ProtoReflect.Descriptor instead.
func (*FindAllAgentNSRoutesRequest) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{20}
}

type FindAllAgentNSRoutesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NsRoutes []*NSRoute `protobuf:"bytes,1,rep,name=nsRoutes,proto3" json:"nsRoutes,omitempty"`
}

func (x *FindAllAgentNSRoutesResponse) Reset() {
	*x = FindAllAgentNSRoutesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_ns_route_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllAgentNSRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllAgentNSRoutesResponse) ProtoMessage() {}

func (x *FindAllAgentNSRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_ns_route_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllAgentNSRoutesResponse.ProtoReflect.Descriptor instead.
func (*FindAllAgentNSRoutesResponse) Descriptor() ([]byte, []int) {
	return file_service_ns_route_proto_rawDescGZIP(), []int{21}
}

func (x *FindAllAgentNSRoutesResponse) GetNsRoutes() []*NSRoute {
	if x != nil {
		return x.NsRoutes
	}
	return nil
}

var File_service_ns_route_proto protoreflect.FileDescriptor

var file_service_ns_route_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x73, 0x5f, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x1b, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x5f, 0x6e, 0x73, 0x5f, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8a, 0x02, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e,
	0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x6e, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x6e, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x6e, 0x73, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0a, 0x6e, 0x73, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72,
	0x61, 0x6e, 0x67, 0x65, 0x73, 0x4a, 0x53, 0x4f, 0x4e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x4a, 0x53, 0x4f, 0x4e, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69,
	0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x2c, 0x0a, 0x11, 0x6e, 0x73, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x11, 0x6e, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x22, 0x35, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x53, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x73,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e,
	0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x22, 0xe2, 0x01, 0x0a, 0x14, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x4a, 0x53, 0x4f,
	0x4e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x4a,
	0x53, 0x4f, 0x4e, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12,
	0x2c, 0x0a, 0x11, 0x6e, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x6e, 0x73, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x4f,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x4f, 0x6e, 0x22, 0x34, 0x0a,
	0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e, 0x73, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x53, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x73, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e, 0x73,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x4e,
	0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25,
	0x0a, 0x07, 0x6e, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x07, 0x6e, 0x73,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x22, 0x73, 0x0a, 0x17, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c,
	0x6c, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6e, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x73, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6e, 0x73, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xa0, 0x01, 0x0a, 0x16, 0x46,
	0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6e, 0x73, 0x43, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x73, 0x44, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6e, 0x73, 0x44,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x2c, 0x0a, 0x11, 0x6e, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x6e, 0x73, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x22, 0x42, 0x0a,
	0x17, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x6e, 0x73, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e,
	0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x08, 0x6e, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x46, 0x0a, 0x1b, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27,
	0x0a, 0x08, 0x6e, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x08, 0x6e,
	0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x22, 0x3c, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a, 0x6e, 0x73, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x49, 0x64, 0x73, 0x22, 0x4f, 0x0a, 0x1f, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x53, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x73, 0x41, 0x66, 0x74, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x4b, 0x0a, 0x20, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x53,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x41, 0x66, 0x74, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x6e, 0x73,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x62, 0x2e, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x08, 0x6e, 0x73, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x26, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x52, 0x0a,
	0x27, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x57,
	0x6f, 0x72, 0x6c, 0x64, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x6e, 0x73, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e,
	0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x08, 0x6e, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x73, 0x22, 0x2a, 0x0a, 0x28, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x43, 0x68, 0x69, 0x6e, 0x61, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x54, 0x0a,
	0x29, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43,
	0x68, 0x69, 0x6e, 0x61, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x6e, 0x73,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70,
	0x62, 0x2e, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x08, 0x6e, 0x73, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x73, 0x22, 0x20, 0x0a, 0x1e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x53, 0x50, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4a, 0x0a, 0x1f, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x53, 0x50, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x6e, 0x73, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e,
	0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x08, 0x6e, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x73, 0x22, 0x1d, 0x0a, 0x1b, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x47, 0x0a, 0x1c, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x27, 0x0a, 0x08, 0x6e, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52,
	0x08, 0x6e, 0x73, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x32, 0xe5, 0x08, 0x0a, 0x0e, 0x4e, 0x53,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0d,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x18, 0x2e,
	0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x39, 0x0a, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x53, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e,
	0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x50, 0x43, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x39, 0x0a,
	0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x18,
	0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x50,
	0x43, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x3e, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x64,
	0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x10, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x41, 0x6c, 0x6c, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x70,
	0x62, 0x2e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x50, 0x43, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4a, 0x0a, 0x0f, 0x66, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4e,
	0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x4e, 0x53, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x15, 0x66,
	0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4e, 0x53, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x13, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e,
	0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x1e, 0x2e, 0x70,
	0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x70,
	0x62, 0x2e, 0x52, 0x50, 0x43, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x65, 0x0a, 0x18,
	0x6c, 0x69, 0x73, 0x74, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x41, 0x66, 0x74, 0x65,
	0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x41, 0x66, 0x74, 0x65, 0x72, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e,
	0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x41,
	0x66, 0x74, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x7a, 0x0a, 0x1f, 0x66, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x12, 0x2a, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64,
	0x41, 0x6c, 0x6c, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x80, 0x01, 0x0a, 0x21, 0x66, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x44, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x43, 0x68, 0x69, 0x6e, 0x61, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x52,
	0x6f, 0x75, 0x74, 0x65, 0x73, 0x12, 0x2c, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41,
	0x6c, 0x6c, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x68, 0x69, 0x6e, 0x61, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c,
	0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x68, 0x69, 0x6e, 0x61, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x62, 0x0a, 0x17, 0x66, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x44, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x49, 0x53, 0x50, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x12, 0x22, 0x2e,
	0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x49, 0x53, 0x50, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x49, 0x53, 0x50, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x14, 0x66, 0x69, 0x6e, 0x64, 0x41, 0x6c,
	0x6c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x12, 0x1f,
	0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x4e, 0x53, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_service_ns_route_proto_rawDescOnce sync.Once
	file_service_ns_route_proto_rawDescData = file_service_ns_route_proto_rawDesc
)

func file_service_ns_route_proto_rawDescGZIP() []byte {
	file_service_ns_route_proto_rawDescOnce.Do(func() {
		file_service_ns_route_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_ns_route_proto_rawDescData)
	})
	return file_service_ns_route_proto_rawDescData
}

var file_service_ns_route_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_service_ns_route_proto_goTypes = []interface{}{
	(*CreateNSRouteRequest)(nil),                      // 0: pb.CreateNSRouteRequest
	(*CreateNSRouteResponse)(nil),                     // 1: pb.CreateNSRouteResponse
	(*UpdateNSRouteRequest)(nil),                      // 2: pb.UpdateNSRouteRequest
	(*DeleteNSRouteRequest)(nil),                      // 3: pb.DeleteNSRouteRequest
	(*FindNSRouteRequest)(nil),                        // 4: pb.FindNSRouteRequest
	(*FindNSRouteResponse)(nil),                       // 5: pb.FindNSRouteResponse
	(*CountAllNSRoutesRequest)(nil),                   // 6: pb.CountAllNSRoutesRequest
	(*FindAllNSRoutesRequest)(nil),                    // 7: pb.FindAllNSRoutesRequest
	(*FindAllNSRoutesResponse)(nil),                   // 8: pb.FindAllNSRoutesResponse
	(*FindAllPublicRoutesRequest)(nil),                // 9: pb.FindAllPublicRoutesRequest
	(*FindAllPublicRoutesResponse)(nil),               // 10: pb.FindAllPublicRoutesResponse
	(*UpdateNSRouteOrdersRequest)(nil),                // 11: pb.UpdateNSRouteOrdersRequest
	(*ListNSRoutesAfterVersionRequest)(nil),           // 12: pb.ListNSRoutesAfterVersionRequest
	(*ListNSRoutesAfterVersionResponse)(nil),          // 13: pb.ListNSRoutesAfterVersionResponse
	(*FindAllDefaultWorldRegionRoutesRequest)(nil),    // 14: pb.FindAllDefaultWorldRegionRoutesRequest
	(*FindAllDefaultWorldRegionRoutesResponse)(nil),   // 15: pb.FindAllDefaultWorldRegionRoutesResponse
	(*FindAllDefaultChinaProvinceRoutesRequest)(nil),  // 16: pb.FindAllDefaultChinaProvinceRoutesRequest
	(*FindAllDefaultChinaProvinceRoutesResponse)(nil), // 17: pb.FindAllDefaultChinaProvinceRoutesResponse
	(*FindAllDefaultISPRoutesRequest)(nil),            // 18: pb.FindAllDefaultISPRoutesRequest
	(*FindAllDefaultISPRoutesResponse)(nil),           // 19: pb.FindAllDefaultISPRoutesResponse
	(*FindAllAgentNSRoutesRequest)(nil),               // 20: pb.FindAllAgentNSRoutesRequest
	(*FindAllAgentNSRoutesResponse)(nil),              // 21: pb.FindAllAgentNSRoutesResponse
	(*NSRoute)(nil),                                   // 22: pb.NSRoute
	(*RPCSuccess)(nil),                                // 23: pb.RPCSuccess
	(*RPCCountResponse)(nil),                          // 24: pb.RPCCountResponse
}
var file_service_ns_route_proto_depIdxs = []int32{
	22, // 0: pb.FindNSRouteResponse.nsRoute:type_name -> pb.NSRoute
	22, // 1: pb.FindAllNSRoutesResponse.nsRoutes:type_name -> pb.NSRoute
	22, // 2: pb.FindAllPublicRoutesResponse.nsRoutes:type_name -> pb.NSRoute
	22, // 3: pb.ListNSRoutesAfterVersionResponse.nsRoutes:type_name -> pb.NSRoute
	22, // 4: pb.FindAllDefaultWorldRegionRoutesResponse.nsRoutes:type_name -> pb.NSRoute
	22, // 5: pb.FindAllDefaultChinaProvinceRoutesResponse.nsRoutes:type_name -> pb.NSRoute
	22, // 6: pb.FindAllDefaultISPRoutesResponse.nsRoutes:type_name -> pb.NSRoute
	22, // 7: pb.FindAllAgentNSRoutesResponse.nsRoutes:type_name -> pb.NSRoute
	0,  // 8: pb.NSRouteService.createNSRoute:input_type -> pb.CreateNSRouteRequest
	2,  // 9: pb.NSRouteService.updateNSRoute:input_type -> pb.UpdateNSRouteRequest
	3,  // 10: pb.NSRouteService.deleteNSRoute:input_type -> pb.DeleteNSRouteRequest
	4,  // 11: pb.NSRouteService.findNSRoute:input_type -> pb.FindNSRouteRequest
	6,  // 12: pb.NSRouteService.countAllNSRoutes:input_type -> pb.CountAllNSRoutesRequest
	7,  // 13: pb.NSRouteService.findAllNSRoutes:input_type -> pb.FindAllNSRoutesRequest
	9,  // 14: pb.NSRouteService.findAllPublicNSRoutes:input_type -> pb.FindAllPublicRoutesRequest
	11, // 15: pb.NSRouteService.updateNSRouteOrders:input_type -> pb.UpdateNSRouteOrdersRequest
	12, // 16: pb.NSRouteService.listNSRoutesAfterVersion:input_type -> pb.ListNSRoutesAfterVersionRequest
	14, // 17: pb.NSRouteService.findAllDefaultWorldRegionRoutes:input_type -> pb.FindAllDefaultWorldRegionRoutesRequest
	16, // 18: pb.NSRouteService.findAllDefaultChinaProvinceRoutes:input_type -> pb.FindAllDefaultChinaProvinceRoutesRequest
	18, // 19: pb.NSRouteService.findAllDefaultISPRoutes:input_type -> pb.FindAllDefaultISPRoutesRequest
	20, // 20: pb.NSRouteService.findAllAgentNSRoutes:input_type -> pb.FindAllAgentNSRoutesRequest
	1,  // 21: pb.NSRouteService.createNSRoute:output_type -> pb.CreateNSRouteResponse
	23, // 22: pb.NSRouteService.updateNSRoute:output_type -> pb.RPCSuccess
	23, // 23: pb.NSRouteService.deleteNSRoute:output_type -> pb.RPCSuccess
	5,  // 24: pb.NSRouteService.findNSRoute:output_type -> pb.FindNSRouteResponse
	24, // 25: pb.NSRouteService.countAllNSRoutes:output_type -> pb.RPCCountResponse
	8,  // 26: pb.NSRouteService.findAllNSRoutes:output_type -> pb.FindAllNSRoutesResponse
	10, // 27: pb.NSRouteService.findAllPublicNSRoutes:output_type -> pb.FindAllPublicRoutesResponse
	23, // 28: pb.NSRouteService.updateNSRouteOrders:output_type -> pb.RPCSuccess
	13, // 29: pb.NSRouteService.listNSRoutesAfterVersion:output_type -> pb.ListNSRoutesAfterVersionResponse
	15, // 30: pb.NSRouteService.findAllDefaultWorldRegionRoutes:output_type -> pb.FindAllDefaultWorldRegionRoutesResponse
	17, // 31: pb.NSRouteService.findAllDefaultChinaProvinceRoutes:output_type -> pb.FindAllDefaultChinaProvinceRoutesResponse
	19, // 32: pb.NSRouteService.findAllDefaultISPRoutes:output_type -> pb.FindAllDefaultISPRoutesResponse
	21, // 33: pb.NSRouteService.findAllAgentNSRoutes:output_type -> pb.FindAllAgentNSRoutesResponse
	21, // [21:34] is the sub-list for method output_type
	8,  // [8:21] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_service_ns_route_proto_init() }
func file_service_ns_route_proto_init() {
	if File_service_ns_route_proto != nil {
		return
	}
	file_models_model_ns_route_proto_init()
	file_models_rpc_messages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_ns_route_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNSRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateNSRouteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNSRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteNSRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindNSRouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindNSRouteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountAllNSRoutesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllNSRoutesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllNSRoutesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllPublicRoutesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllPublicRoutesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateNSRouteOrdersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNSRoutesAfterVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListNSRoutesAfterVersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllDefaultWorldRegionRoutesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllDefaultWorldRegionRoutesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllDefaultChinaProvinceRoutesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllDefaultChinaProvinceRoutesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllDefaultISPRoutesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllDefaultISPRoutesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllAgentNSRoutesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_ns_route_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllAgentNSRoutesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_ns_route_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_ns_route_proto_goTypes,
		DependencyIndexes: file_service_ns_route_proto_depIdxs,
		MessageInfos:      file_service_ns_route_proto_msgTypes,
	}.Build()
	File_service_ns_route_proto = out.File
	file_service_ns_route_proto_rawDesc = nil
	file_service_ns_route_proto_goTypes = nil
	file_service_ns_route_proto_depIdxs = nil
}
